disabled_rules:
- weak_delegate
- railing_whitespace
- identifier_name
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
function_parameter_count:
    warning: 6
type_body_length:
    warning: 300
file_length:
    warning: 1000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
reporter: "xcode"
