name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  install_dependency:
    name: Install dependency
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Gems
        id: cache-gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Cache Pods
        id: cache-pods
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Build Pods
        if: steps.cache-pods.outputs.cache-hit != 'true'
        run: bundle exec pod install
  
  swift_lint:
    name: SwiftLint
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Swiftlint
        id: swift-lint
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-swiftlint

      - name: Install Swiftlint
        if: steps.swift-lint.outputs.cache-hit != 'true'
        run: brew install swiftlint

      - name: Run Swiftlint
        run: swiftlint

  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
